server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

springfox:
  documentation:
    enabled: true