version: '3'

services:
  postgres:
    image: postgres:12.1
    ports:
      - "15430:5432"
    healthcheck:
      interval: 1s
      timeout: 30s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: pismo_transaction_manager
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  pgdata: